/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.avro.entity;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Author extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Author\",\"namespace\":\"com.avro.entity\",\"fields\":[{\"name\":\"name\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Author() {}

  /**
   * All-args constructor.
   */
  public Author(java.lang.CharSequence name) {
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /** Creates a new Author RecordBuilder */
  public static com.avro.entity.Author.Builder newBuilder() {
    return new com.avro.entity.Author.Builder();
  }
  
  /** Creates a new Author RecordBuilder by copying an existing Builder */
  public static com.avro.entity.Author.Builder newBuilder(com.avro.entity.Author.Builder other) {
    return new com.avro.entity.Author.Builder(other);
  }
  
  /** Creates a new Author RecordBuilder by copying an existing Author instance */
  public static com.avro.entity.Author.Builder newBuilder(com.avro.entity.Author other) {
    return new com.avro.entity.Author.Builder(other);
  }
  
  /**
   * RecordBuilder for Author instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Author>
    implements org.apache.avro.data.RecordBuilder<Author> {

    private java.lang.CharSequence name;

    /** Creates a new Builder */
    private Builder() {
      super(com.avro.entity.Author.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.avro.entity.Author.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Author instance */
    private Builder(com.avro.entity.Author other) {
            super(com.avro.entity.Author.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.avro.entity.Author.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.avro.entity.Author.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    public Author build() {
      try {
        Author record = new Author();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
